# Generated by Django 4.0.6 on 2022-08-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_created_by_alter_category_updated_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='date_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='date_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='date_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
