# Generated by Django 4.0.6 on 2022-08-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_category_id_products_category_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discription',
            field=models.TextField(null=True),
        ),
    ]
