# Generated by Django 4.0.6 on 2022-08-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='product_id',
            new_name='product',
        ),
    ]
