# Generated by Django 4.0.6 on 2022-08-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_subcategory_category_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
