# Generated by Django 4.0.6 on 2022-08-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_category_slug_products_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
    ]
