# Generated by Django 4.0.6 on 2022-08-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_products_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
