# Generated by Django 4.0.6 on 2022-08-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_products_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand',
        ),
    ]
