# Generated by Django 4.0.6 on 2022-09-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_cart_product_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_total',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True),
        ),
    ]
