# Generated by Django 4.0.6 on 2022-09-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_cart_product_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_total',
        ),
    ]
