# Generated by Django 4.0.6 on 2022-09-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_cart_product_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_total',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
