# Generated by Django 4.0.6 on 2022-09-19 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_date_at_category_created_at_and_more'),
        ('customer', '0007_cart_product_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='products.subcategory'),
        ),
    ]
