# Generated by Django 4.0.6 on 2022-09-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_cart_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
    ]
