# Generated by Django 4.0.6 on 2022-09-20 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_date_at_category_created_at_and_more'),
        ('customer', '0009_remove_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suze', to='products.subcategory'),
        ),
    ]
