# Generated by Django 4.0.6 on 2022-09-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_cart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_total',
            field=models.BigIntegerField(blank=True, default=1, null=True),
        ),
    ]
