# Generated by Django 4.0.6 on 2022-09-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered')], default='pending', max_length=200, null=True),
        ),
    ]
